api:
  image: docker.io/clusterpulse/clusterpulse-api:v0.2.2
frontend:
  image: docker.io/clusterpulse/clusterpulse-ui:v0.2.0
policyEngine:
  image: docker.io/clusterpulse/clusterpulse-policy-controller:v0.2.2
clusterEngine:
  image: docker.io/clusterpulse/clusterpulse-cluster-controller:v0.2.2
redis:
  image:
    tag: latest
